#  _   _                      _                 _ 
# | | | |_   _ _ __  _ __| | __ _ _ __   __| |
# | |_| | | | | '_ \| '__| |/ _` | '_ \ / _` |
# |  _  | |_| | |_) | |  | | (_| | | | | (_| |
# |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
#        |___/|_|                             
# Configuração Minimalista do Phoenix

# 1. MONITORES
monitor=,preferred,auto,auto

# 2. VARIÁVEIS DE CAMINHO
$configs = $HOME/.dotfiles/hypr

# 3. IMPORTAR MÓDULOS
source = $configs/options.conf
source = $configs/keybinds.conf
source = $configs/startup.conf

# 4. REGRAS DE JANELA (Opcional por enquanto)
# Se você tiver regras específicas, pode criar um windowrules.conf depois
