# --- ESSENCIAIS DO SISTEMA ---
# Garante que o Wayland e o Desktop Portal conversem bem (essencial para compartilhamento de tela)
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Gerenciador de Autenticação (O Polkit permite que apps peçam sua senha em janelas gráficas)
# Nota: Verifique se o caminho do seu polkit é este ou aponte para o executável direto (/usr/lib/...)
exec-once = $HOME/.config/hypr/scripts/Polkit.sh

# --- INTERFACE ---
exec-once = swww-daemon --format xrgb # Gerenciador de Wallpaper
exec-once = waybar                    # Sua barra superior
exec-once = swaync                    # Central de Notificações
exec-once = hypridle                  # Gerenciador de inatividade (suspender/bloquear)

# --- UTILITÁRIOS ---
exec-once = nm-applet --indicator     # Ícone de rede na systray
exec-once = blueman-applet             # Ícone de bluetooth na systray

# Gerenciador de Área de Transferência (Clipboard)
# Permite que você copie várias coisas e escolha depois com um atalho
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# --- INICIALIZAÇÃO DE TEMA ---
# Aqui você pode colocar o comando para o swww carregar um wallpaper fixo inicialmente
# exec-once = swww img /caminho/para/sua/imagem.jpg
